name: check-builds
run-name: ${{ github.actor }} is trying to push code that needs to be checked.
on: [push]
branches: 
- working

jobs:
	build-ubermain:
		runs-on: rachel-spectator
		steps:
			- uses: actions/checkout
			- run: scons -c --build=UberMain
			- run: scons --build=UberMain
